name: Screener Earnings Scraper

on:
  schedule:
    - cron: "30 13 * * *"
  workflow_dispatch:

jobs:
  run-screener-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clean old node_modules and lockfile
        run: rm -rf node_modules package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run Screener Scraper
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: node index.js
